### PR TITLE
Refactored generation of environment.yaml to make it easier to read

### PR DESCRIPTION
**Pull request by andywis**

### CODE REVIEW

**Comment by stevemul** [comment]
Does the pipeline run like this? If so it looks good to me, I'm just wondering if you need explicit line endings in the new code or not.

**Review by k8soneill — DISMISSED** [review]
LGTM

**Comment by stevemul** [comment]
Sorry @andywis - this needs to be rebased to the master branch now, there was an outstanding PR that needed merged (the one you suggested these changes in funnily enough. Can you resolve the conflicts and we can re-test. At the moment its not passing the tests as it still has the old deploy.sh variables.

**Review by stevemul — DISMISSED** [review]
Needs to be rebased from master really - the deploy command is the old one at the moment.

**Comment by andywis** [comment]
In response to your earlier comment, we no longer need the explicit line endings, and echo automatically adds one. 
From the docs: "Normally, each echo command prints a terminal newline, but the -n option suppresses this." -- https://www.tldp.org/LDP/abs/html/internal.html

**Comment by andywis** [comment]
Changed as per stevemul's request. Awaiting test run.

**Comment by andywis** [comment]
Build #21 on mgmt.farn00006 completed successfully.

**Review by stevemul — APPROVED** [review]
lgtm

**Pull request merged**
